function New-PublishPayloadFragment {
    <#
    .SYNOPSIS
      Generates a WiX v5 fragment (PublishPayload.g.wxs): one component per published file,
      preserving subdirectories (satellites like id\NeyraOptimizer.resources.dll keep their folder).
      Deterministic GUIDs derived from relative paths keep rebuilds stable.
    #>
    param(
        [Parameter(Mandatory)] [string] $PublishDir,
        [Parameter(Mandatory)] [string] $OutputPath,
        [Parameter(Mandatory)] [string] $ExeName
    )

    function New-StableGuid([string] $seed) {
        $md5 = [System.Security.Cryptography.MD5]::Create()
        $hash = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($seed))
        $g = [guid]::new($hash)
        return '{' + $g.ToString().ToUpperInvariant() + '}'
    }

    function New-SafeId([string] $raw) {
        return ($raw -replace '[^A-Za-z0-9_]', '_')
    }

    $resolvedPublish = (Resolve-Path -LiteralPath $PublishDir).Path.TrimEnd('\') + '\'
    $files = Get-ChildItem -LiteralPath $PublishDir -Recurse -File |
        Where-Object { $_.Name -ne $ExeName } |
        Sort-Object FullName

    # relDir -> list of files ; relDir -> child relDirs
    $filesByDir = @{}
    $childDirs = @{}
    $allDirs = New-Object System.Collections.Generic.List[string]

    foreach ($f in $files) {
        $rel = $f.FullName.Substring($resolvedPublish.Length)
        $relDir = Split-Path -Parent $rel
        if ($null -eq $relDir) { $relDir = '' }

        if (-not $filesByDir.ContainsKey($relDir)) { $filesByDir[$relDir] = @() }
        $filesByDir[$relDir] += @{ Rel = $rel; Full = $f.FullName }

        $parts = @()
        if ($relDir -ne '') { $parts = $relDir -split '[\\/]' }
        $accum = ''
        foreach ($p in $parts) {
            $parentKey = $accum
            if ($accum -eq '') { $accum = $p } else { $accum = "$accum\$p" }
            if (-not $allDirs.Contains($accum)) { $allDirs.Add($accum) }
            if (-not $childDirs.ContainsKey($parentKey)) { $childDirs[$parentKey] = @() }
            if (-not (($childDirs[$parentKey]) -contains $accum)) { $childDirs[$parentKey] += $accum }
        }
    }

    $sb = [System.Text.StringBuilder]::new()
    $componentIds = New-Object System.Collections.Generic.List[string]
    $indent = '      '

    function Write-Component([object] $entry) {
        $script:sb = $sb
        $componentId = 'CMP_' + ((New-SafeId ($entry.Rel -replace '[\\/]', '__')) -replace '\.', '_')
        $guid = New-StableGuid ($entry.Rel.ToLowerInvariant())
        [void]$sb.AppendLine("$indent        <Component Id=`"$componentId`" Guid=`"$guid`">")
        [void]$sb.AppendLine("$indent          <File Source=`"$($entry.Full)`" />")
        [void]$sb.AppendLine("$indent        </Component>")
        $componentIds.Add($componentId)
    }

    function Write-DirTree([string] $dirKey) {
        if ($dirKey -ne '') {
            $name = ($dirKey -split '[\\/]')[-1]
            $id = 'DIR_' + (New-SafeId ($dirKey -replace '[\\/]', '__'))
            [void]$sb.AppendLine("$indent      <Directory Id=`"$id`" Name=`"$name`">")
        }
        foreach ($entry in ($filesByDir[$dirKey] | Sort-Object Rel)) { Write-Component $entry }
        foreach ($child in ($childDirs[$dirKey] | Sort-Object)) { Write-DirTree $child }
        if ($dirKey -ne '') {
            [void]$sb.AppendLine("$indent      </Directory>")
        }
    }

    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<!-- AUTO-GENERATED by scripts/build-installer.ps1 — do not edit. -->')
    [void]$sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')

    # ── Fragment 1: layout under INSTALLFOLDER + components ──
    [void]$sb.AppendLine('  <Fragment>')
    [void]$sb.AppendLine('    <DirectoryRef Id="INSTALLFOLDER">')
    Write-DirTree ''
    [void]$sb.AppendLine('    </DirectoryRef>')
    [void]$sb.AppendLine('  </Fragment>')

    # ── Fragment 2: group consumed by <Feature> ──
    [void]$sb.AppendLine('  <Fragment>')
    [void]$sb.AppendLine('    <ComponentGroup Id="PublishPayload">')
    foreach ($cid in $componentIds) {
        [void]$sb.AppendLine("      <ComponentRef Id=`"$cid`" />")
    }
    [void]$sb.AppendLine('    </ComponentGroup>')
    [void]$sb.AppendLine('  </Fragment>')

    [void]$sb.AppendLine('</Wix>')

    $outDir = Split-Path -Parent $OutputPath
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
    [System.IO.File]::WriteAllText($OutputPath, $sb.ToString())
    Write-Host "   payload fragment: $($files.Count) files -> $OutputPath"
}

Export-ModuleMember -Function New-PublishPayloadFragment
